repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((blinkpy|tests)/.+)?[^/]+\.py$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.0.0
        files: ^(blinkpy|tests)/.+\.py$
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
      - id: rst-linter
        files: /.+\.rst$
